import { initMenu } from "./modules/menu";
import { initHero } from "./modules/hero";
import { initInteractions } from "./modules/interactions";
import { initPageTransitions } from "./modules/page-transitions";
import { initRelatedProducts } from "./modules/related-products";
import { initScrollTrigger } from "./modules/scroll-trigger";
import { initTextSlider } from "./modules/text-slider";
import { initAccordions } from "./modules/accordions";
import { initMoments } from "./modules/moments";
import { initScrollingAnimations } from "./modules/scroll-animations";
import { initPolicyStyles } from "./modules/policy-styles";
import { initScrollingGallery } from "./modules/scrolling-gallery";
import { initWellbeing } from "./modules/wellbeing";
import { initBlog } from "./modules/blog";
import { initCustomCursor } from "./modules/custom-cursor";

// initInteractions();
// initHero();
// initScrollTrigger();
// initPageTransitions();
// initRelatedProducts();
// initMenu();
// initTextSlider();
// initAccordions();
// initMoments();
// initScrollingAnimations();
// initPolicyStyles();
// initScrollingGallery();
// initWellbeing();
// initBlog();
// initCustomCursor();