import { initHeroAnimation } from "./modules/hero-animation";
import { initMenu } from "./modules/menu";
import { initInteractions } from "./modules/interactions";
import { initPageTransitions } from "./modules/page-transitions";
import { initRelatedProducts } from "./modules/related-products";
import { initScrollTrigger } from "./modules/scroll-trigger";
import { initTextSlider } from "./modules/text-slider";
import { initAccordions } from "./modules/accordions";
import { initScrollingAnimations } from "./modules/scroll-animations";
import { initScrollingGallery } from "./modules/scrolling-gallery";
import { initBlog } from "./modules/blog";
import { initCustomCursor } from "./modules/custom-cursor";

initHeroAnimation();
// initInteractions();
// initScrollTrigger();
// initPageTransitions();
// initRelatedProducts();
// initMenu();
// initTextSlider();
// initAccordions();
// initScrollingAnimations();
// initScrollingGallery();
// initBlog();
// initCustomCursor();